package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/ZanzyTHEbar/errbuilder-go"
	"github.com/spf13/cobra"
)

type initOptions struct {
	OutputDir  string
	Name       string
	Force      bool
	ConfigOnly bool
}

func newInitCommand() *cobra.Command {
	opts := initOptions{}
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold a new product spec with sensible defaults",
		Long: `Generate a product.yaml file with inline schema, inline profile,
and spec defaults sections pre-configured. This gives you a working
single-file product spec that you can customize.`,
		RunE: func(_ *cobra.Command, _ []string) error {
			return runInit(opts)
		},
	}

	cmd.Flags().StringVar(&opts.OutputDir, "dir", ".", "Directory to write product.yaml into")
	cmd.Flags().StringVar(&opts.Name, "name", "", "Product name (defaults to directory name)")
	cmd.Flags().BoolVar(&opts.Force, "force", false, "Overwrite existing file(s)")
	cmd.Flags().BoolVar(&opts.ConfigOnly, "config", false, "Generate avular-packages.yaml config file instead of product spec")

	return cmd
}

func runInit(opts initOptions) error {
	dir := opts.OutputDir
	if dir == "" {
		dir = "."
	}

	if opts.ConfigOnly {
		return writeConfigScaffold(dir, opts.Force)
	}

	return writeProductScaffold(dir, opts.Name, opts.Force)
}

func writeProductScaffold(dir, name string, force bool) error {
	outPath := filepath.Join(dir, "product.yaml")

	if !force {
		if _, err := os.Stat(outPath); err == nil {
			return errbuilder.New().
				WithCode(errbuilder.CodeAlreadyExists).
				WithMsg("product.yaml already exists; use --force to overwrite")
		}
	}

	if name == "" {
		absDir, err := filepath.Abs(dir)
		if err == nil {
			name = filepath.Base(absDir)
		} else {
			name = "my-product"
		}
	}

	content := generateProductScaffold(name)

	if err := os.MkdirAll(dir, 0o750); err != nil {
		return errbuilder.New().
			WithCode(errbuilder.CodeInternal).
			WithMsg("failed to create output directory").
			WithCause(err)
	}

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return errbuilder.New().
			WithCode(errbuilder.CodeInternal).
			WithMsg("failed to write product.yaml").
			WithCause(err)
	}

	fmt.Printf("created: %s\n", outPath)
	return nil
}

func writeConfigScaffold(dir string, force bool) error {
	outPath := filepath.Join(dir, "avular-packages.yaml")

	if !force {
		if _, err := os.Stat(outPath); err == nil {
			return errbuilder.New().
				WithCode(errbuilder.CodeAlreadyExists).
				WithMsg("avular-packages.yaml already exists; use --force to overwrite")
		}
	}

	if err := os.MkdirAll(dir, 0o750); err != nil {
		return errbuilder.New().
			WithCode(errbuilder.CodeInternal).
			WithMsg("failed to create output directory").
			WithCause(err)
	}

	content := generateConfigScaffold()

	if err := os.WriteFile(outPath, []byte(content), 0644); err != nil {
		return errbuilder.New().
			WithCode(errbuilder.CodeInternal).
			WithMsg("failed to write avular-packages.yaml").
			WithCause(err)
	}

	fmt.Printf("created: %s\n", outPath)
	return nil
}

func generateProductScaffold(name string) string {
	return `# Product specification for ` + name + `
# Generated by: avular-packages init
#
# This is a single-file product spec with inline schema, inline profile,
# and defaults.  Customize it to match your project.
#
# Usage:
#   avular-packages resolve                    # auto-discovers this file
#   avular-packages resolve --product product.yaml
#   avular-packages build --output out

api_version: "v1"
kind: "product"
metadata:
  name: "` + name + `"
  version: "0.1.0"
  owners:
    - "team"

# Defaults eliminate the need for repetitive CLI flags.
# CLI flags always override these when provided.
defaults:
  target_ubuntu: "24.04"
  workspace:
    - "."
  # repo_index: "repo-index.yaml"
  output: "out"

# Inline schema: maps abstract ROS dependency keys to concrete packages.
# Add your project's ROS dependencies here.  File-based schemas in
# a schemas/ directory or listed in schema_files override these per key.
schema:
  schema_version: "v1"
  mappings: {}
  #   rclcpp:
  #     type: apt
  #     package: ros-humble-rclcpp
  #   numpy:
  #     type: pip
  #     package: numpy
  #     version: ">=1.26,<2.0"

# Inline profile: defines packaging policy directly in the product spec.
# For complex projects, extract profiles into separate files instead.
compose:
  - name: "default"
    source: "inline"
    profile:
      inputs:
        package_xml:
          enabled: true
          tags:
            - "debian_depend"
            - "pip_depend"
      packaging:
        groups:
          - name: "apt-runtime"
            mode: "individual"
            scope: "runtime"
            matches:
              - "apt:*"
            targets:
              - "24.04"
          - name: "pip-runtime"
            mode: "meta-bundle"
            scope: "runtime"
            matches:
              - "pip:*"
            targets:
              - "24.04"

# Product-level inputs (merged on top of profile inputs)
inputs:
  package_xml:
    enabled: true
    tags:
      - "debian_depend"
      - "pip_depend"

# Publishing configuration
publish:
  repository:
    name: "` + name + `"
    channel: "dev"
    snapshot_prefix: "` + name + `"
    signing_key: "release-key"
`
}

func generateConfigScaffold() string {
	return `# avular-packages configuration file
# Generated by: avular-packages init --config
#
# Place this file in the project root as avular-packages.yaml,
# or in ~/.config/avular-packages/avular-packages.yaml for user-wide defaults.
#
# Precedence (highest to lowest):
#   1. CLI flags
#   2. Environment variables (AVULAR_PACKAGES_*)
#   3. This config file
#   4. Product spec defaults section
#
# Environment variables use the prefix AVULAR_PACKAGES_ with underscored
# key names, e.g.:
#   AVULAR_PACKAGES_PRODUCT=./product.yaml
#   AVULAR_PACKAGES_TARGET_UBUNTU=24.04

# Path to product spec (overrides auto-discovery)
# product: "product.yaml"

# Profile spec path(s)
# profiles:
#   - "profiles/base.yaml"

# Workspace root(s) to scan for package.xml files
# workspace:
#   - "."

# Repository index file path
# repo_index: "repo-index.yaml"

# Output directory for resolve/build artifacts
# output: "out"

# Target Ubuntu release for dependency resolution
# target_ubuntu: "24.04"

# Schema mapping file(s) for ROS tag resolution
# schema_files:
#   - "schemas/ros-humble.yaml"

# PIP index URL override for build
# pip_index_url: ""

# Directory containing prebuilt internal debs
# internal_deb_dir: ""

# Internal package source directories
# internal_src: []

# Emit apt preferences pin file from apt.lock
# apt_preferences: false

# Emit apt-get install command from apt.lock
# apt_install_list: false

# Resolve apt versions with SAT-based dependency closure
# apt_sat_solver: false

# Snapshot apt source configuration
# snapshot_apt_sources: false
# snapshot_apt_base_url: ""
# snapshot_apt_component: "main"
# snapshot_apt_arch: []
`
}
